###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "2.0"
services:

    phpngx:
      image: nginx:alpine
      working_dir: /application
      volumes:
        - ./app:/application
        - ./phpdocker/nginx/xdebug:/etc/nginx/xdebug
        - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        -  ./ssh_certs:/etc/nginx/certs
#        - ../traefik/certs:/etc/nginx/certs
      ports:
        - "8060:443"
        - "8061:80"
        - "8063:443"
      restart: "always"
      depends_on:
        - phpapp
      networks:
        - php-network

    phpapp:
      build: phpdocker/php-fpm
#      image: jackfrost2014/php7fpm-tourenplanung:tourenplanung-php-fpm
      working_dir: /application
      volumes:
        - ./app:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
        - ./phpdocker/php-fpm/xdebug.ini:/etc/php/7.2/fpm/conf.d/20-xdebug.ini
      restart: "always"
      environment:
        - PHP_IDE_CONFIG=serverName=mytime.local
      networks:
        - php-network

## Does actually not work, docker exits on start with error
## could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
networks:
  php-network:
    driver: bridge
