FROM phpdockerio/php72-fpm:latest
WORKDIR "/application"

# Fix debconf warnings upon build
ARG DEBIAN_FRONTEND=noninteractive

# Install selected extensions and other stuff
RUN apt-get update \
    && apt-get -y --no-install-recommends \
    install \
    php-memcached php7.2-mysql php-redis php-xdebug \
    php7.2-gd php7.2-imap php7.2-intl php7.2-ldap \
    php-mongodb php7.2-phpdbg php-ssh2 php-tideways \
    php7.2-xsl php-yaml \
    php-pear \
    apt-transport-https \
    apt-utils \
    libcurl3 

# https://github.com/Microsoft/msphpsql/issues/751


# add msodbcsql packages - you can set APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE to a non-empty value to disable warnings
# https://stackoverflow.com/questions/48162574/how-to-circumvent-apt-key-output-should-not-be-parsed?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
RUN APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=Y \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
# install msodbcsql and associated tools
    && ACCEPT_EULA=Y apt-get install -y msodbcsql17 \
    && ACCEPT_EULA=Y apt-get install -y mssql-tools \
# add msssql-tools to path 
    && echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile \
    && echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc \
    && apt-get install -y unixodbc-dev \
# add extension info to ini files
    && echo extension=pdo_sqlsrv.so >> `php --ini | grep "Scan for additional .ini files" | sed -e "s|.*:\s*||"`/30-pdo_sqlsrv.ini \
    && echo extension=sqlsrv.so >> `php --ini | grep "Scan for additional .ini files" | sed -e "s|.*:\s*||"`/20-sqlsrv.ini \
# install sqlsrv
    && pecl install sqlsrv \
    && pecl install pdo_sqlsrv

# copy 30-pdo_sqlsrv.ini to some locations for loading
#RUN cp /etc/php/7.2/cli/conf.d/30-pdo_sqlsrv.ini /etc/php/7.2/fpm/conf.d

# install locales (sqlcmd will have a fit if you don't have this)
#RUN apt-get install -y locales && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && locale-gen

RUN apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*
